// This page has all the actions possible with redux. These are utilized in ActionCreators and in reducer files

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_TEXTUREDETAIL = 'SET_TEXTUREDETAIL'
export const GET_PLANETID = 'GET_PLANETID'
export const SET_PLANETDETAIL = 'SET_PLANETDETAIL'
export const SET_PLANET = 'SET_PLANET'
export const SET_PLANETBUILDQUE = 'SET_PLANETBUILDQUE'
export const SET_PLANETRESEARCHQUE = 'SET_PLANETRESEARCHQUE'
export const SET_PLANETSHIPQUE = 'SET_PLANETSHIPQUE'
export const SET_PLANETSTATS = 'SET_PLANETSTATS'
export const SET_BUILDINGSTATS = 'SET_BUILDINGSTATS'
export const SET_RESEARCHTYPES = 'SET_RESEARCHTYPES'
export const SET_RESEARCHSTATS = 'SET_RESEARCHSTATS'
export const SET_RESETUSER = 'SET_RESETUSER'
export const SET_RESETPLANETYPE = 'SET_RESETPLANETYPE'
export const SET_RESETPLANET = 'SET_RESETPLANET'
export const SET_PLANETPOP = 'SET_PLANETPOP'





