// This page has all the actions possible with redux. These are utilized in ActionCreators and in reducer files

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_TEXTUREDETAIL = 'SET_TEXTUREDETAIL'
export const GET_PLANETID = 'GET_PLANETID'
export const SET_PLANETDETAIL = 'SET_PLANETDETAIL'
export const SET_PLANET = 'SET_PLANET'
export const SET_PLANETBUILDQUE = 'SET_PLANETBUILDQUE'
export const SET_PLANETRESEARCHQUE = 'SET_PLANETRESEARCHQUE'
export const SET_PLANETSHIPQUE = 'SET_PLANETSHIPQUE'
export const SET_PLANETSTATS = 'SET_PLANETSTATS'
export const SET_BUILDINGSTATS = 'SET_BUILDINGSTATS'
export const SET_RESEARCHTYPES = 'SET_RESEARCHTYPES'
export const SET_RESEARCHSTATS = 'SET_RESEARCHSTATS'
export const SET_RESETUSER = 'SET_RESETUSER'
export const SET_RESETPLANET = 'SET_RESETPLANET'
export const SET_PLANETPOP = 'SET_PLANETPOP'
export const SET_SHIPDESIGNS = 'SET_SHIPDESIGNS'
export const SET_SHIPPODS = 'SET_SHIPPODS'
export const SET_SHIPHULLS = 'SET_SHIPHULLS'
export const SET_USERFLEETS = 'SET_USERFLEETS'
export const SET_PLANETFLEETS = 'SET_PLANETFLEETS'
export const SET_CURRENTDESIGNS = 'SET_CURRENTDESIGNS'
export const SET_USERPLANETS = 'SET_USERPLANETS'
export const SET_PLANETLIST = 'SET_PLANETLIST'
export const SET_GALAXY1 = 'SET_GALAXY1'
export const SET_GALAXY2 = 'SET_GALAXY2'
export const SET_GALAXY3 = 'SET_GALAXY3'
export const SET_SYSTEMFLEETS = 'SET_SYSTEMFLEETS'
export const SET_SELECTEDFLEET = 'SET_SELECTEDFLEET'





